---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/tags: rpm-build
  name: get-rpm-sources
spec:
  description: |-
    Download source files referenced by a spec file.
  params:
    - description: Package name to clone
      name: package-name
      type: string
    - description: The Trusted Artifact URI pointing to the artifact with the source code.
      name: source-artifact
      type: string
    - name: ociStorage
      description: The OCI repository where the Trusted Artifacts are stored.
      type: string
    - name: ociArtifactExpiresAfter
      description: How long Trusted Artifacts should be retained
      type: string
    - description: RPM Build environment OCI image to run scripts in
      name: script-environment-image
      type: string
  results:
    - name: dependencies-artifact
      description: The Trusted Artifact URI pointing to the artifact with the rpm deps and source.
      type: string
  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
  steps:
    - name: use-trusted-artifact
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:9b180776a41d9a22a1c51539f1647c60defbbd55b44bbebdd4130e33512d8b0d
      args:
        - use
        - $(params.source-artifact)=/var/workdir/source
    - name: download
      image: $(params.script-environment-image)
      script: |
        set -x
        cd "/var/workdir/source"
        dist-git-client --forked-from https://src.fedoraproject.org/rpms/$(params.package-name) sources
    - name: create-trusted-artifact
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:9b180776a41d9a22a1c51539f1647c60defbbd55b44bbebdd4130e33512d8b0d
      args:
        - create
        - --store
        - $(params.ociStorage)
        - $(results.dependencies-artifact.path)=/var/workdir/source
      env:
        - name: IMAGE_EXPIRES_AFTER
          value: $(params.ociArtifactExpiresAfter)
  volumes:
    - name: workdir
      emptyDir: {}
