---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/konflux-ci/rpmbuild-pipeline?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: pipelines
    appstudio.openshift.io/component: ci-for-pipeline
    pipelines.appstudio.openshift.io/type: build
  name: ci-for-pipeline-on-pull-request
  namespace: rpm-build-pipeline-tenant
spec:
  params:
    - name: package-name
      value: cpio
    - name: git-url
      value: https://github.com/praiskup/example-upstream-konflux-cpio.git
    - name: revision
      value: use-patchN
    - name: target-branch
      value: "main"
    - name: self-ref-revision
      value: "{{ revision }}"
    - name: self-ref-url
      value: "{{ source_url }}"
    - name: test-suffix
      value: -rpmbuild-pipeline
    - name: ociStorage
      value: quay.io/redhat-user-workloads/rpm-build-pipeline-tenant/ci-for-pipeline:on-pr-cpio-{{ revision }}
    - name: script-environment-image
      value: quay.io/redhat-user-workloads/rpm-build-pipeline-tenant/environment:on-pr-39570ddc03858d127fdf4824ebf3eded06f132cf
    - name: build-architectures
      value:
        - aarch64
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "{{ source_url }}"
      - name: revision
        value: "{{ revision }}"
      - name: pathInRepo
        value: pipeline/build-rpm-package.yaml
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
